# SEO settings
title: "Darkmatter"
description: "A minimalist Jekyll theme for Technical Writing and Ranting."
keywords: "Jekyll, theme, open source, download, SEO, web, minimalist, hobbyist, darkmatter"
url: https://github.com/fellowhobbyist/darkmatter-theme #site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
repo: https://github.com/fellowhobbyist/darkmatter-theme
#disqus_shortname: "FellowHobbyist"
#twitter_username: "FelloWHobbyist"
#comments: true

# Build settings
#permalink   : /:year/:title/
permalink: /:title/
markdown    : kramdown
highlighter : rouge

kramdown:
    syntax_highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed # expanded

include: ['_pages']

# Author settings
author:
  name     : "Brian Hooper"
  job      : "Open Source Practitioner and Technology Professional"
  bio      : "Skilled Practitioner focused on advanced business capabilities delivered through Open Source Technology and Cloud Based Services"
  thumb    : /images/author.jpg
  email    : afellowhobbyist@gmail.com
  url      : http://fellowhobbyist.github.io
  github   : http://github.com/fellowhobbyist
  twitter  : http://twitter.com/fellowhobbyist
  linkedin : http://linkedin.com/in/fellowhobbyist

plugins: [jekyll-paginate]